# Generated by Django 4.2.8 on 2023-12-14 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_address_customuser_login_cnt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='recent_login',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reg_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
    ]
