# Generated by Django 4.2.8 on 2023-12-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_recent_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='restriction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
