# Generated by Django 4.2.8 on 2023-12-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_restriction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='restriction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
