# Generated by Django 4.2.8 on 2023-12-14 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_restriction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='restriction_date',
        ),
    ]
