# Generated by Django 4.2.8 on 2023-12-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='doi',
        ),
        migrations.AddField(
            model_name='journal',
            name='ack',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
