# Generated by Django 4.2.8 on 2023-12-19 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_remove_journal_doi_journal_ack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='all_authors',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='file',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='pub_year',
        ),
    ]
