# Generated by Django 4.2.8 on 2023-12-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_remove_journal_all_authors_remove_journal_extras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='all_authors',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='extras',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='papers/'),
        ),
        migrations.AddField(
            model_name='journal',
            name='pub_year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
