# Generated by Django 4.2.8 on 2023-12-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='position',
            field=models.IntegerField(choices=[(1, 'PROFESSOR'), (2, 'POSTDOC'), (3, 'FULL-TIME')], default=1),
        ),
        migrations.AlterField(
            model_name='bio',
            name='career',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
