# Generated by Django 4.2.8 on 2023-12-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_bio_position_alter_bio_career'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='positions',
        ),
    ]
