# Generated by Django 4.2.8 on 2023-12-19 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_bio_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='user',
        ),
    ]
