# Generated by Django 4.2.8 on 2023-12-19 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0006_bio_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bio', to=settings.AUTH_USER_MODEL),
        ),
    ]
